### ISSUE TITLE
It doesn't show HP in numeric and dispellable debuffs

### ISSUE THREAD

**Issue by LEOMODE** [BullseiWoWAddons/BattleGroundEnemies#14]
This will be a critical feature so we can quickly glance who the enemies are and what their HP's are. Also just like the WoW default party frame, it would be good to show dispellable debuffs so we can only focus on what to dispel. Last but not least, it'll be nice if we can make the HP bar size different for 10-15 or 25-40 separately.

**Comment by bullsei** [comment]
Hi, 
So you want numeric values on the healthbar? wouldnt that be too much clutter? With all the stuff thats already there, name, role icon, target indicator  etc, i woudln't know where to fit that extra information.
In the latest alpha i implemented a feature in the aura section > filters, here you can select a blizzard like filter, this means it will apply the same filters on the frame as blizzard uses for their raidframes. HP bars are already seperate for 1-15 and 16-40 players (go to allies|enemies > 1-15 > Bar settings, there you can select teh height

**Comment by LEOMODE** [comment]
Thanks for your reply. 
Actually for Blizzard default frame, showing health number on top of the health bar (which is simply an overlay) doesn't hurt for viewing purposes. In fact, it helps even better because we quickly know who to target (29k health vs 43k health). Now your statement could make sense if there is already a health % value and asking for health number value on top of it. I think just a simple overlay to show either in the middle, all the way on the left, or all the way on the right could suffice. And you can actually make the health bar bigger to make it look even less clutter in your view. 

I will also try your 2nd and 3rd suggestion. Thanks again.

**Comment by LukasGrove** [comment]
@bullsei 
I know this thread is a bit old, but I happened to post a similar request on the curseforge page, was hoping to accomplish something like max hp rounded to the nearest thousand, like "Someguy-40k". That way it doesn't take up too much room, but makes it easy to target call.

**Comment by bullsei** [comment]
new version is out and it offers the option to add health text

**Comment by bullsei** [comment]
Closing this because both features have been added a few versions ago. If there is still something wrong or you would like to see changed feel free to create a new issue.
