### ISSUE TITLE
About update prompt in the new version of 9.0.5.6

### ISSUE THREAD

**Issue by ZoraZora59** [BullseiWoWAddons/BattleGroundEnemies#16]
I downloaded the latest version of this plugin on https://www.curseforge.com/wow/addons/battlegroundenemies, the version is 9.0.5.6.
When I was playing the game, the plug-in kept reminding me that there was a new version to download. If you can, please let me know where to download in the prompt

**Comment by cpbowman1** [comment]
I'm having this issue too

**Comment by bullsei** [comment]
closing since this is fixed
