### ISSUE TITLE
BGsize bug

### ISSUE THREAD

**Issue by Addonman** [BullseiWoWAddons/BattleGroundEnemies#19]
Message: ..\AddOns\BattleGroundEnemies\Main.lua line 1624:
   attempt to index field 'bgSizeConfig' (a nil value)
Debug:
   [string "@RCLootCouncil\Classes\Services\ErrorHandler.lua"]:149:
      ...dOns\RCLootCouncil\Classes\Services\ErrorHandler.lua:147
   [string "@WagoAnalytics\WagoAnalytics.lua"]:72:
      WagoAnalytics\WagoAnalytics.lua:70
   [string "=[C]"]: ?
   [string "@BattleGroundEnemies\Main.lua"]:1624: UpdatePlayerCount()
   [string "@BattleGroundEnemies\Main.lua"]:3310: ?()
   [string "@BattleGroundEnemies\Main.lua"]:127:
      BattleGroundEnemies\Main.lua:124

**Comment by bullsei** [comment]
Will be fixed in the next release
