### ISSUE TITLE
Lua error after invite/invited to grp 

### ISSUE THREAD

**Issue by Maas1337** [BullseiWoWAddons/BattleGroundEnemies#20]
Hello there!

Version: BattleGroundEnemies-9.2.0.7

i got an error after i get invited to a 3 party group.  (2player + me)

https://pastebin.com/BwHCLjbA

Thank you :)

**Comment by Maas1337** [comment]
now i invited someone in group and then this error 
https://pastebin.com/iBPEHuT8

**Comment by bullsei** [comment]
Hey, thanks for the report, i already fixed this in 9.2.0.8 since this error was also reported on curseforge :) check it out and let me know if it works

**Comment by Maas1337** [comment]
seems to be fixxed, thanks from mars1337 and maas1337 :)

**Comment by bullsei** [comment]
Thanks for letting me know :) damn it, i butchered your name in the commit :D
