### ISSUE TITLE
error after leaving arena

### ISSUE THREAD

**Issue by Maas1337** [BullseiWoWAddons/BattleGroundEnemies#21]
https://pastebin.com/iSizEVjv

thank you :)

**Comment by bullsei** [comment]
Hmm, thats definitly a new one. Is this on TBC? I looked into the code and couldn't figure out what could have gone wrong. Does this error happen every time you leave a arena? I did some arenas on Retail and never had that error happen.

**Comment by Maas1337** [comment]
Hey, yes tbc. Its not everytime (think about 10% Chance) . Got it with 2 man grp and 5 man grp.

**Comment by bullsei** [comment]
I looked at the code a bit more and i still couldn't figure out what could have went wrong there :( i uploaded a new version that prints out some stuff into the chat if that error is happening (The lua error itself is gone now). Would be nice if you could tell me the messages, hopefully with that information i can figure out what goes wrong.

**Comment by Maas1337** [comment]
seems good at this moment ^^

**Comment by bullsei** [comment]
Okay great, let me know if that changes

**Comment by Maas1337** [comment]
https://pastebin.com/1nbMe4vG

**Comment by bullsei** [comment]
okay, i reworked this function a few days ago, this should definitely fix that issue. i am currently working on implementing some other bigger chances aswell. New version should be ready in a few days or a week

**Comment by bullsei** [comment]
closing since this should definitely be fixed by the new releases
