### ISSUE TITLE
Filtering for Debuff has some bugs:

### ISSUE THREAD

**Issue by cretch21** [BullseiWoWAddons/BattleGroundEnemies#22]
Filter by Dispellability isn't working (it's showing the debuffs regardless of dispellability status)
Filter by Debuff type isn't working (it's showing all the types of debuffs regardless of debuff type selected)
Filter by SpellID isn't working at all. Although its possible I could be entering the incorrect SpellID, I tried entering all the different possibilities for a Moonfire and nothing worked.

Edit: I love your addon! It's great, and I didn't want to forget to include my gratitude.

**Comment by bullsei** [comment]
The filtering should funny work since a few days ago. Do you still found any issues?

**Comment by bullsei** [comment]
Closing this because both features have been added a few versions ago. If there is still something wrong or you would like to see changed feel free to create a new issue.
