### ISSUE TITLE
No Longer Supported??

### ISSUE THREAD

**Issue by Firsthunterz** [BullseiWoWAddons/BattleGroundEnemies#23]
This seems to be no longer supported on WotLK Classic as well as the Curseforge Client. Please update or fix this!!! This addon is a MUST for pvp

**Comment by bullsei** [comment]
Hi. As far as I know this addon still works. It just needs a version update and some small fixes. I was working on it a while ago but then I lost a bit of interest again and I haven't played wow that much. But I try to work on it in the next week and check what's going on. I am sorry for not being very active on the development lately but this is just a hobby, but I understand that many people depend on it so I try to get it back in shape. Feel free to remind me again if let's say there isn't still a update in like a month or so :)

**Comment by hiiipowerbass** [comment]
Can you confirm if it is supported in WOTLK? this is the singular addon that is absolutely essential to mine and so many more WoW gameplay experiences. many thanks!

**Comment by hiiipowerbass** [comment]
p.s. it no longer shows on curse client or wowup

**Comment by bullsei** [comment]
yeah, that could be possible, i am working on a working version. I haven't  played any TBC myself and my character is level 30 or so but i feel like the addon would work with my current version i got so far. I just uploaded a new alpha version, so there might be some things that are not 100% perfekt yet. but it should be running so far, but some alignments could be off or different from before, also some of the new features aren't fully implemented yet, but it should be good enough to run. I need to test more and fix all the upcoming problems. 
it would be nice if you could give it a try on wotlk and let me know if there are any errors, or anything that doesnt work as expected.

**Comment by hiiipowerbass** [comment]
Will get back to you when I get into some bg's :)

**Comment by bullsei** [comment]
Closing this because the addon is fully operational since a few releases ago. If there is still something wrong or you would like to see changed feel free to create a new issue.
