### ISSUE TITLE
Default blizzard debuff duration

### ISSUE THREAD

**Issue by JordanK295** [BullseiWoWAddons/BattleGroundEnemies#25]
Amazing addon btw, I appreciate all the options you have added.

One addition I would love is for the "blizzard-style" desaturation on buffs/debuffs, like in the image below.

![image](https://user-images.githubusercontent.com/72442216/210193074-b371cab3-6ccd-48b6-8e30-60a3b2799815.png)

**Comment by bullsei** [comment]
HI, I will add an option for this. Will be included in the next release.

**Comment by bullsei** [comment]
i just noticed this issue. i will work on implementing an option for it. Sorry for being away for that long

**Comment by JordanK295** [comment]
Thanks for the recent work here, just a cheeky bump on this.

**Comment by bullsei** [comment]
oh dang, thanks for the bumb. i am bad at keeping track of thigs in wanted to do.

**Comment by bullsei** [comment]
Added this feature in the coming release. Let me know if thats what you expected. I also could add an option to choose the color of the swipe if needed
