### ISSUE TITLE
Add-on interferes with Macro Creation

### ISSUE THREAD

**Issue by jbreedlove5** [BullseiWoWAddons/BattleGroundEnemies#26]
I have several add-ons installed for WoW. I noticed last week that when I tried to create a new macro I received an error via chat that an add-on interfered and must be disabled. I turned off all add-ons and I could create a new macro. I started turning them on one by one and could create a new macro until I got to battlegroundenemies. This add-on was not allowing me to create a new macros. I disabled it again and I was able to create new macros. I turn it on until I need to create a new macro and then I turn it off. I did not notice this issue until last week and created several macros the week before. Just letting you know of an issue that I noticed as I really love the add-on and it is very helpful in battlegrounds. thanks

**Comment by bullsei** [comment]
Hey, thanks for the report, i havent had this issue myself yet. Are you refering to classic or retail wow?

**Comment by jbreedlove5** [comment]
It is on retail. thanks

**Comment by bullsei** [comment]
Hey, i could figure out the issue and fix it. The fix will be included in the next release. Thank you for the report

**Comment by jbreedlove5** [comment]
Awesome. Thank you so much.

**Comment by bullsei** [comment]
New release has been released. Sorry my my lack of work on this addon. If you face any issues please let me know

**Comment by bullsei** [comment]
will close this for now since its fixed. Feel free to create more tickets if you notice any issues
