### ISSUE TITLE
Disable arena frames no longer works

### ISSUE THREAD

**Issue by Kennahz** [BullseiWoWAddons/BattleGroundEnemies#27]
Using the options "Disable arena frames in arena" and "Disable arena frames in battleground" no longer function.

**Comment by bullsei** [comment]
Hey, yeah i noticed this too, fix will be in new release

**Comment by Kennahz** [comment]
awesome thanks!

**Comment by Kennahz** [comment]
was also wondering if we could get a separate option to disable the pet frames in arena/bg ? it'd be cool to keep frames but the pet frames are almost always useless lol

**Comment by bullsei** [comment]
So a new release has been pushed out, This contains the fix for this problem as well. I had it implemtend for a long time but now it finally made it into the release after being away from working on the addon. If you still have any issues let me know :)

**Comment by Kennahz** [comment]
seems the disable arena frames in arena still not working. thank you for pushing out an update though!

**Comment by bullsei** [comment]
okay, maybe blizzard changed stuff again there. I actually fixed it like almost a year ago and back then it worked. I will test it and see whats up and push out a new version soon

**Comment by bullsei** [comment]
oh yes, so there is a new arena frame now :D Its more square and has a new name. I will change the code to hide that :)

**Comment by bullsei** [comment]
i uploaded a new release that should hide the new frames

**Comment by Kennahz** [comment]
it works but its backwards. it hides them when its unchecked, and shows them when the box is checkmarked. it works though, thank you!

**Comment by bullsei** [comment]
yeah, its fixed in latest release, i mixed it up for some reason

**Comment by bullsei** [comment]
will close this for now. Feel free to create more tickets if you notice any issues
