### ISSUE TITLE
click casting support?

### ISSUE THREAD

**Issue by bonesoul** [BullseiWoWAddons/BattleGroundEnemies#28]
is there way to enable battlegroundenemies to work with blizzard's default click casting?

**Comment by bullsei** [comment]
I will look into this aswell, i can probably make it work. Stay tuned :)

**Comment by bullsei** [comment]
got it working. But it will only work for group members.

**Comment by bullsei** [comment]
New version has been released which also works with this new feature :) But keep in mind its only possiblel on allies

**Comment by bullsei** [comment]
closed since implemented. Feel free to create a new ticket for bugs or feature requests
