### ISSUE TITLE
10.2 Addon Action Blocked Error

### ISSUE THREAD

**Issue by Kyreaper** [BullseiWoWAddons/BattleGroundEnemies#33]
11/25/2023 - 

**Addon Version**
10.0.2.6

Game Version: 10.2.0.52188, Retail, US, English 

I have been receiving the following error at random in all sorts of content, from open-world content to dungeon content, not just BG's or instanced PvP. 

~

1x [ADDON_ACTION_BLOCKED] AddOn 'BattleGroundEnemies' tried to call the protected function 'IsItemInRange()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: ?
[string "@BattleGroundEnemies/Main.lua"]:523: in function `UpdateAll'
[string "@BattleGroundEnemies/Main.lua"]:606: in function `NewUnitID'
[string "@BattleGroundEnemies/Main.lua"]:3993: in function `UpdateAllUnitIDs'
[string "@BattleGroundEnemies/Main.lua"]:4042: in function `GROUP_ROSTER_UPDATE'
[string "@BattleGroundEnemies/Main.lua"]:2737: in function `?'
[string "@Accountant_Classic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Accountant_Classic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...sic/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Accountant_Classic/Libs/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@BattleGroundEnemies/Libs/LibGroupInSpecT-1.1-92/LibGroupInSpecT-1.1.lua"]:671: in function `eventhandler'
[string "@BattleGroundEnemies/Libs/LibGroupInSpecT-1.1-92/LibGroupInSpecT-1.1.lua"]:129: in function <...ies/Libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:127>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

~

Screenshots below are from BugGrabber / BugSack:
![11-25-2023 BG Enemies Error (1)](https://github.com/BullseiWoWAddons/BattleGroundEnemies/assets/12869693/f6442dba-9594-46e2-92aa-9f161b273ccf)
![11-25-2023 BG Enemies Error (2)](https://github.com/BullseiWoWAddons/BattleGroundEnemies/assets/12869693/10beaef6-3c1d-4661-a5b1-d2281289b0f7)
![11-25-2023 BG Enemies Error (3)](https://github.com/BullseiWoWAddons/BattleGroundEnemies/assets/12869693/b16b8fe0-7331-40df-a75a-5a90f29364fb)

**Comment by bullsei** [comment]
Hey, thanks for the report. I am back working on the addon and getting all the problems resolved. This error is due to Blizzards new restrictions in combat.

**Comment by bullsei** [comment]
Hey, this issue should be fixed in the newest relase. Let me know if you still face any issues or errors

**Comment by bullsei** [comment]
will close this for now since its fixed. Feel free to create more tickets if you notice any issues
