### ISSUE TITLE
"Higher transparency when out of set Range" Issue.

### ISSUE THREAD

**Issue by dnskzkv** [BullseiWoWAddons/BattleGroundEnemies#34]
Hey!

Seems lika an addon do not see "range" and "Higher transparency when out of set Range" do not work after 10.2 update.
Is it possible to fix, or Blizzard blocked something in 10.2?

BTW addon is awesome thanks for your work!

**Comment by bullsei** [comment]
Hey, yes Blizzard has blocked addons from getting range information from other players while in combat using items. I will change the addon to no longer rely on items for range checking, this will reduce the amount of possible ranges but the most used range of 40 yards/meters will be working while in combat. 
Maybe Blizzard will change its mind again take back that change, but we will see.

**Comment by dnskzkv** [comment]
> Hey, yes Blizzard has blocked addons from getting range information from other players while in combat using items. I will change the addon to no longer rely on items for range checking, this will reduce the amount of possible ranges but the most used range of 40 yards/meters will be working while in combat. Maybe Blizzard will change its mind again take back that change, but we will see.

Got it! Thank you anyway! It was really convenient feature to play BGs...

**Comment by bullsei** [comment]
I just uploaded a new release. I think i got all the issues reported in the last months fixed. If you still notice an issue please let me know :)

**Comment by bullsei** [comment]
closed since fixed. Feel free to create a new issue for anything you notice
