### ISSUE TITLE
focus on rclick, supported?

### ISSUE THREAD

**Issue by masterkain** [BullseiWoWAddons/BattleGroundEnemies#35]
thanks for this addon, I'm going to try it in arena and replace default frames and gladiusex, however before doing so I figured I'll ask here because I did not find a related option: are the frames clickable somehow? Ideally I'd like to right click to set a focus.

I've seen https://github.com/BullseiWoWAddons/BattleGroundEnemies/commit/3b674b6560148efef92d6d35939341ef2d0b8d52 so I guess it should work?

**Comment by bullsei** [comment]
definitely, its the default, left click to target, right click to focus

**Comment by masterkain** [comment]
thanks, gonna try!
