### ISSUE TITLE
SOD Lua Error

### ISSUE THREAD

**Issue by 1Botnet** [BullseiWoWAddons/BattleGroundEnemies#36]
3658x Blizzard_ArenaUI/Blizzard_ArenaUI.lua:93: attempt to index global 'ArenaEnemyFrames' (a nil value)
[string "@Blizzard_ArenaUI/Blizzard_ArenaUI.lua"]:93: in function `ArenaEnemyFrames_UpdateVisible'
[string "@Blizzard_ArenaUI/Blizzard_ArenaUI.lua"]:179: in function `ArenaEnemyFrame_UpdatePlayer'
[string "@Blizzard_ArenaUI/Blizzard_ArenaUI.lua"]:218: in function <Blizzard_ArenaUI/Blizzard_ArenaUI.lua:212>

Locals:
_ = true
instanceType = "pvp"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ArenaEnemyFrames' (a nil value)"

Doesn't matter if I turn off the arena tab

**Comment by bullsei** [comment]
will close because resolved
