### ISSUE TITLE
UpdateEnemiesFromCombatlogScanning  It seems there's a mistake; 

### ISSUE THREAD

**Issue by zzwtest** [BullseiWoWAddons/BattleGroundEnemies#39]
function BattleGroundEnemies:UpdateEnemiesFromCombatlogScanning()
	**self.Enemies.BeforePlayerSourceUpdate(PlayerSources.CombatLog)**
	
	
===========
It seems there's a mistake; a colon "."should replace the period ":"

**Comment by bullsei** [comment]
hey, you are correct, made a  typo there, will be fixed in next release
