### ISSUE TITLE
Battle ground ennemy dot tracker

### ISSUE THREAD

**Issue by cl68462** [BullseiWoWAddons/BattleGroundEnemies#40]
Hello, thank you for creating Battlegroundennemies, it's a very useful tool that I've been using for many years.

However, I've recently run into a problem: I'd like to be able to see the Agony debuff in the middle of the enemy life bar, and only that debuff so I can track its cd. I also use Big Debuff, and I understand that there's a correspondence between the two addons (in terms of spell priority), but I can't configure what I'd like.
Could you help me?

Thanks a lot! @bullsei

**Comment by bullsei** [comment]
This should work if you enable custom filtering on the non priority auras. You can filter by spell ID and only add the spell Id of agony there.
