### ISSUE TITLE
11.0.2 Breaking Changes🚨

### ISSUE THREAD

**Issue by rbgdevx** [BullseiWoWAddons/BattleGroundEnemies#41]
They moved GetAddOnMetadata to C_AddOns.GetAddOnMetadata

Also I believe they removed `GetTexCoordsForRoleSmallCircle` from their API but you can get the function to store in your code locally here https://github.com/Ennie/wow-ui-source/blob/14bf2f621a13b04a7ff771e5fcda4d0c8bc533c1/FrameXML/LFGFrame.lua#L531

```
function GetTexCoordsForRoleSmallCircle(role)
	if role == "TANK" then
		return 0, 19 / 64, 22 / 64, 41 / 64
	elseif role == "HEALER" then
		return 20 / 64, 39 / 64, 1 / 64, 20 / 64
	elseif role == "DAMAGER" then
		return 20 / 64, 39 / 64, 22 / 64, 41 / 64
	else
		error("Unknown role: " .. tostring(role))
	end
end
```

**Comment by rbgdevx** [comment]
also Arena frames aren't showing up which i think is a blizzard problem and a temporary one so things like orb stack count and who the flag carrier is doesnt work atm since its based off of that.

**Comment by masterkain** [comment]
```
10x BattleGroundEnemies/Main.lua:2379: attempt to call global 'UnitAura' (a nil value)
[string "@BattleGroundEnemies/Main.lua"]:2379: in function <BattleGroundEnemies/Main.lua:2374>
[string "@BattleGroundEnemies/Main.lua"]:2421: in function `ShowAuraTooltip'
[string "@BattleGroundEnemies/Modules/Auras.lua"]:419: in function `func'
[string "@BattleGroundEnemies/Main.lua"]:2362: in function `ShowTooltip'
[string "@BattleGroundEnemies/Modules/Auras.lua"]:418: in function <BattleGroundEnemies/Modules/Auras.lua:417>

Locals:
unitID = "arena2"
spellId = 2645
filter = "HELPFUL"
(for index) = 1
(for limit) = 40
(for step) = 1
i = 1
(*temporary) = nil
(*temporary) = "arena2"
(*temporary) = 1
(*temporary) = "HELPFUL"
(*temporary) = "attempt to call global 'UnitAura' (a nil value)"

```

**Comment by rbgdevx** [comment]
Looks like `UnitAura` was deprecated:

> This function was deprecated in patch 10.2.5 and will be removed in patch 11.0.2.

see https://warcraft.wiki.gg/wiki/API_UnitAura.

in favor of `C_UnitAuras.GetAuraDataByIndex`, see https://warcraft.wiki.gg/wiki/API_C_UnitAuras.GetAuraDataByIndex

**Comment by bullsei** [comment]
hey guys, thanks for the reports, i am currently working on implementing the api changes and get this thing running again :)

**Comment by rbgdevx** [comment]
Thank you! I've been passing around a working version with the fixes as a temporary measure, people will be very excited to get the official fixes in! thanks again!

**Comment by bullsei** [comment]
Just pushed out a new alpha, haven't had much time to test everything but i feel like i could have got all the changes. Feel free to test it :) don't have more time to text today but will most likely make it to full release tomorrow

**Comment by bullsei** [comment]
Just tested it in a random bg and everything seems to work. If you notice any issue with newest release please let me know

**Comment by rbgdevx** [comment]
looks good to me! and blizzard fixed the arena frames not showing up so the orb percentages and who has flag on flag maps work again, ty!

**Comment by bullsei** [comment]
i noticed the dr tracker is broken but i figured out the issue and will most likely release a fix for that tomorrow

**Comment by masterkain** [comment]
```
10x bad argument #1 to '?' (Usage: local definitionInfo = C_Traits.GetDefinitionInfo(definitionID))
[string "=[C]"]: in function `GetDefinitionInfo'
[string "@BattleGroundEnemies/Libs/LibGroupInSpecT-1.1-95/LibGroupInSpecT-1.1.lua"]:345: in function `GetCachedTalentInfoByID'
[string "@BattleGroundEnemies/Libs/LibGroupInSpecT-1.1-95/LibGroupInSpecT-1.1.lua"]:599: in function `BuildInfo'
[string "@BattleGroundEnemies/Libs/LibGroupInSpecT-1.1-95/LibGroupInSpecT-1.1.lua"]:281: in function `eventhandler'
[string "@BattleGroundEnemies/Libs/LibGroupInSpecT-1.1-95/LibGroupInSpecT-1.1.lua"]:131: in function <...ies/Libs/LibGroupInSpecT-1.1/LibGroupInSpecT-1.1.lua:129>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local definitionInfo = C_Traits.GetDefinitionInfo(definitionID))"
```

I also have this one on beta

**Comment by bullsei** [comment]
okay, this should get resolved in the next release when LibGroupInSpecT gets an update
