### ISSUE TITLE
[Feature Request] Hide Blizzard raid frames in battlegrounds

### ISSUE THREAD

**Issue by RealJig** [BullseiWoWAddons/BattleGroundEnemies#42]
It would be nice if the raid frames were automatically hidden in BGs

![image](https://github.com/user-attachments/assets/21d533d9-c224-457f-bfbf-ef63c61e621c)

**Comment by bullsei** [comment]
i will add an option for this in the next release

**Comment by bullsei** [comment]
This is now implemented in version 11.0.5.1. Will close this for now, if you notice any problems feel free to create a new issue
