### ISSUE TITLE
Missing localization print message

### ISSUE THREAD

**Issue by rbgdevx** [BullseiWoWAddons/BattleGroundEnemies#47]
Getting this message currently, for a while actually:

![image](https://github.com/user-attachments/assets/ae20b6ed-22dd-42fb-811b-c0eb869077a2)

**Comment by bullsei** [comment]
yeah, this is something that can be safely ignored for now. its just a reminder for myself during development that i forgot to add a new phrase to the localization system :) I don't know why i thought its a good idea to bring this reminder into the actual release code and spam the chat :D

**Comment by rbgdevx** [comment]
ahhh, all good, ty! yea im sure there's a better way but i put a debug variable into my config so i can leave all my print code and toggle it on/off privately with the addons i make.

**Comment by bullsei** [comment]
new version 11.0.5.0 removes this message :)
