### ISSUE TITLE
User message told to report

### ISSUE THREAD

**Issue by oliwhi** [BullseiWoWAddons/BattleGroundEnemies#49]
Message was

`BattleGroundEnemies: Missing localization entry for['PlayerCount_Enabled']. Please report this to addon author.`

**Comment by oliwhi** [comment]
I am noticing no problems in game, if I do I will follow up

**Comment by nbafatherlolsky** [comment]
i meat it too for many times
![L}~MWGFMZRC43)B) TSBQMC](https://github.com/user-attachments/assets/3980c8ab-dcaf-44d4-988c-ef5e678f1838)

**Comment by bullsei** [comment]
hey guys, don't worry about that for now, it will be gone in the next version, its just meant as a reminder for myself to add localization. No eta yet but until then just ignore it :)

**Comment by bullsei** [comment]
This mesage is gone in 11.0.5.0
