### ISSUE TITLE
Deephaul Crystal in Deephaul Ravine

### ISSUE THREAD

**Issue by jwest592** [BullseiWoWAddons/BattleGroundEnemies#50]
In the Deephaul Ravine when someone picks up the Deephaul Crystal you cant see the Deephaul Crystal on BGE. Can you add the Deephaul Crystal to BGE please 
 
Deephaul Crystal - 434339

**Comment by bullsei** [comment]
hey, thanks for teh request, will be added in the new release

**Comment by bullsei** [comment]
This is now implemented in version 11.0.5.1. Will close this for now, if you notice any problems feel free to create a new issue
