### ISSUE TITLE
Stealthed Enemy Occasionally Disappears from BGE in First Round of Solo Shuffle

### ISSUE THREAD

**Issue by RaphanW** [BullseiWoWAddons/BattleGroundEnemies#55]
This appears new since the recent update.

The addon doesn't appear to be throwing a LUA error when this happens. I don't have a much better description than the title.

I use BGE (enemies only, not teammates) for arenas, including solo shuffle.  

If an enemy is stealth at the start of round 1, sometimes the frames remove them and only display 2 enemies instead of all 3 for the rest of round 1. 

I have seen this 2-3 times over the past few days. I have never seen it in a round other than round 1 or with unstealthed enemies.

I debated reporting this because it's not consistent and I don't know how to 100% reproduce it (especially since that probably requires randomly pairing vs. a stealth enemy). I'm not sure if this impacts regular arenas since I haven't played them much this week. 

However, you requested feedback about the update.  If someone else is reading this and encounters this same issue please reply for confirmation.

**Comment by bullsei** [comment]
okay, thank you for letting  me know, i will test this out, hopefully i can reproduce it, don't worry about it not being 100% clear on how to trigger it, but your description is good enough so i know what to look for.

**Comment by bullsei** [comment]
Does this still happen with the latets version? i did quite some solo shuffles but i never got a stealthy in first round...

**Comment by RaphanW** [comment]
I have not encountered it since the most recent update and I've done quite a few shuffles since then.

**Comment by bullsei** [comment]
okay, good to hear, if anything in terms of solo shuffle or in general could be improved let me know

**Comment by RaphanW** [comment]
OK, will do. Nothing jumps to mind at the moment.

Thanks a bunch for the addon!

**Comment by bullsei** [comment]
allright, no worries, i am glad you like it: )   feel free to reply to this if this problem occurs again
