### ISSUE TITLE
Medallions are not working

### ISSUE THREAD

**Issue by l3uGsY** [BullseiWoWAddons/BattleGroundEnemies#6]
Since Pre-Patch, Medallion changed to an item, [Corrupted Aspirant's Medallion] and is not registering.

I imagine the same applies for [Corrupted Aspirant's Sigil of Adaptation]

**Comment by bullsei** [comment]
Thanks for the report, i played a bit around with it but i couldn't figure out how to detect it after the changes. I think i would have to level up first to figure out how to detect it. 
I Added https://www.wowhead.com/spell=336126/gladiators-medallion 
and https://www.wowhead.com/spell=336135/adaptation
 to the data list for trinkets, maybe this already makes it work again, if not maybe i need to track another event. when you got time to try out the new version please let me know if this already made it work for you. 

Thanks

**Comment by l3uGsY** [comment]
I'll be able to check in a few hours.

**Comment by bullsei** [comment]
Did you get a chance to check it? I didnt hit level 60 myself yet :D

**Comment by l3uGsY** [comment]
Medallion and Relentless is working great.

Adaptation is not.  I have tried every "adaptation" spell id on wowhead, looked for an aura... there is no combat log entry.

I have no clue how to pull a spell id from in game as it goes off.

**Comment by bullsei** [comment]
Okay, thanks for your feedback. i am back home now, when i get some freetime to spare i will do my best to finally level up and check ingame if i can fix that.

**Comment by bullsei** [comment]
Closed since fixed long time ago :D
