### ISSUE TITLE
Trinkets aren't working!

### ISSUE THREAD

**Issue by NicoTheMW** [BullseiWoWAddons/BattleGroundEnemies#8]
Hey! I absolutely -LOVE- your addon! I've been using it every since Battleground Targets stopped working after Legion. After pre-patch, I believe, I noticed it stopped tracking trinkets! I don't know if this is due to trinkets changing from an honor talent to an actual item or just something weird on Blizzard's end! Thank you.

**Comment by bullsei** [comment]
Relentless and normal trinket should work, i haven't seen adaptation yet but I hit 60 like a day ago to see if I can get adaptation to be detected aswell. Are you using the latest version?

**Comment by NicoTheMW** [comment]
I am! None of the trinkets are showing for me for some reason :/

**Comment by bullsei** [comment]
When it also doesn't show up in the testing mode the configuration must be bad. Did you change anything in the configuration lately? Also if you want you can upload your configuration file (BattleGroundEnemies.lua, could be character specific or accountwide depending on your configuration) inside the WTF folder so I can have a look why it doesn't work anymore

**Comment by bullsei** [comment]
closing since no reply for over a year
